### ISSUE TITLE
Space.EndpointSigningKey is required when contacting from space

### ISSUE THREAD

**Issue by Bullrich** [JetBrains/space-app-tutorials#2]
I have followed the instructions and my server is up and running, but when I connect it using `ngrok` from the space app I get the following error:

```
fail: Microsoft.AspNetCore.Diagnostics.DeveloperExceptionPageMiddleware[1]
      An unhandled exception has occurred while executing the request.
      Microsoft.Extensions.Options.OptionsValidationException: Space.EndpointSigningKey is required.; Space.EndpointVerificationToken is required.
```

Do I need to set up the `EndpointSigningKey` somewhere? 
My `appsettings.json` (and the development one) are correctly setup.

Example:
```json
{
  "Logging": {
    "LogLevel": {
      "Default": "Information",
      "Microsoft": "Warning",
      "Microsoft.Hosting.Lifetime": "Information"
    }
  },
  "AllowedHosts": "*",

  "Space": {
    "ServerUrl": "https://company.jetbrains.space",
    "ClientId": "clientId-code",
    "ClientSecret": "client-secret-code",
    "EndpointSigningKey": "EndpointSigningKey-code",
    "EndpointVerificationToken": "EndpointVerificationToken-code"
  }
}
```

**Comment by maartenba** [comment]
The configuration indead has to be set, but also bound in code, e.g. https://github.com/JetBrains/space-app-tutorials/blob/main/dotnet-create-a-chatbot/RemindMeBot/Startup.cs#L38

Can you check this configuration binding is in place?

**Comment by Bullrich** [comment]
Yes, I have this in my code:
![image](https://user-images.githubusercontent.com/8524599/134427205-96bf4e22-9edf-4e30-89ac-d63a8b40e75f.png)

Can I assign it any other way to test if I set it up wrong?

**Comment by maartenba** [comment]
Looks like this may be caused bu the extra brackets in the `Configuration.Bind` call. Try this:

```csharp
services.AddSpaceWebHookHandler<RemindMeBotHandler>(options => Configuration.Bind("Space", options));
```

instead of

```csharp
services.AddSpaceWebHookHandler<RemindMeBotHandler>(options => Configuration.Bind(("Space", options)));
```

**Comment by Bullrich** [comment]
It was that @maartenba. I didn't notice the double parenthesis.

Thank you for your help! I'm very much looking forward to build bots with this API!

**Comment by maartenba** [comment]
Let us know how it goes! Really curious to hear what you are building
